### ISSUE TITLE
Add possiblity to return both country_locale and language locale (with and without lcid standart)

### ISSUE THREAD

**Issue by Sacristan** [Epigene/geo_locale#1]
GeoLocale.country_code should return 
ISO A2 country code  (downcased?) -> http://userpage.chemie.fu-berlin.de/diverse/doc/ISO_3166.html

GeoLocale.locale should have possibility to return both language code (standart -> ISO 639-1) and LCID string
http://www.science.co.il/Language/Locale-codes.asp

for example:
Estonia
GeoLocale.country_code => ee
GeoLocale.locale => et
GeoLocale.locale lcid: true => et

Brazil
GeoLocale.country_code => br
GeoLocale.locale => pt
GeoLocale.locale lcid: true => pt-br

**Comment by Sacristan** [comment]
All is basically on returned country code basis where locale (with its opens) method is basically result of mapped hash values by country code.

Way to possibly store and access language codes:

std_hash (no lcid)
country_code => language_locale
example, 
ee=>et
br=>pt

lcid_hash
country_code => lcid_language_code
ee=>et
br=>pt-br

Method could look like this:

def locale lcid: false
   if lcid
       lcid_hash[country_code]
   else
       std_hash[country_code]
   end
end

**Comment by Epigene** [comment]
Nepieciešama DB, kas mapp country_code ar (default) locale.
Citādi no http://www.science.co.il/Language/Locale-codes.asp novar īsti izdomāt, kādu locale atgriest, ja country code ir, piemēram, lu (luxemburga)

**Comment by Epigene** [comment]
Quick search neko neatrod. Varu izveidot mūsējo, kas noklātu lietotās valstis un valodas, īpaši ee=>et un us=>en

**Comment by Sacristan** [comment]
Ir atrodama -> French - Luxemburg

**Comment by Epigene** [comment]
Since some countries have several languages (Luxemburg having fr-lu and de-lu) one will have to build a hash database to go from country code to a locale code with hand-picked defaults. Perhaps next major release will see me putting in reasonable defaults for most countries and an option to override them at will.
