### ISSUE TITLE
GeoKit unreliable

### ISSUE THREAD

**Issue by Epigene** [Epigene/geo_locale#3]
Yet to see an IP that fails on GeoIP but is foind by GeoKit

Geolocation
  GeoIP
    should return nil for 0.0.0.0
    should return nil for localhost
    should return lv for 81.198.65.13
    should return lt for 77.79.35.98
    should return ee for 188.92.162.172
    should return et for 188.92.162.172 after override
    should return ru for 92.255.197.224
    should return us for 97.77.25.20
    should return gb for 78.157.209.36
    should return ir for 77.104.75.76
    should return pl for 83.3.115.58
  GeoKit
    should return nil for 0.0.0.0
    should return nil for localhost
    should return lv for 81.198.65.13
    should return lt for 77.79.35.98 (FAILED - 1)
    should return ee for 188.92.162.172 (FAILED - 2)
    should return et for 188.92.162.172 after override (FAILED - 3)
    should return ru for 92.255.197.224
    should return us for 97.77.25.20
    should return gb for 78.157.209.36 (FAILED - 4)
    should return ir for 77.104.75.76 (FAILED - 5)
    should return pl for 83.3.115.58

**Comment by Sacristan** [comment]
What Services are You going to use ?

**Comment by Epigene** [comment]
GeoKit left as a redundancy if GeoIP database fails to return a value (though I am 99% sure it, too, will fail to return a value then)
